name: Client CLI Release

on:
  push:
    branches:
      - main
    paths:
      - 'ClientConsole/**'
      - '.github/workflows/ClientCLIRelease.yml'

jobs:
  Release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup C# .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build ClientCLI for Windows
        working-directory: ./ClientConsole
        run: dotnet publish --runtime win-x64 --configuration Release -p:PublishSingleFile=true --self-contained

      - name: Build ClientCLI for Linux
        working-directory: ./ClientConsole
        run: dotnet publish --runtime linux-x64 --configuration Release -p:PublishSingleFile=true --self-contained
      
      - name: Create Release Tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag_prefix: v

      - name: Upload Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          automatic_release_tag: "latest"
          title: Release ${{ steps.tag.outputs.new_tag }}
          prerelease: false
          files: |
            ./ClientConsole/bin/Release/net8.0/win-x64/publish/ClientConsole.exe
            ./ClientConsole/bin/Release/net8.0/linux-x64/publish/ClientConsole
