name: Deploy WebsiteMonitor API (Backend)
 
on:

  push:
    branches:
      - main
    paths:
      - 'Server/**'
      - '.github/workflows/DeployServer.yml'

  workflow_dispatch:
 
jobs:
  Build:
    runs-on: ubuntu-latest

    env: 
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: 'eu-west-1'
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Setup dotnet cli
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
 
      - name: Dotnet publish
        run: |
          dotnet restore;
          dotnet publish -r linux-x64 --configuration "Release" --self-contained "true";
        working-directory: Server
 
      - name: Package artifact
        run: zip -r ../site.zip *
        working-directory: Server/bin/Release/net8.0/linux-x64/publish
 
      - name: Upload artifact to S3
        run: aws s3 cp site.zip s3://${{ secrets.BUCKET_NAME }}/application-${{ github.run_id }}.zip
        working-directory: Server/bin/Release/net8.0/linux-x64
 
  Deploy:
    runs-on: ubuntu-latest

    needs: Build
    env: 
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: 'eu-west-1'
 
    steps:
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name ${{ secrets.BACKEND_APP_NAME }} --version-label ${{ github.run_id }} --source-bundle S3Bucket="${{ secrets.BUCKET_NAME }}",S3Key="application-${{ github.run_id }}.zip"
          aws elasticbeanstalk update-environment --application-name ${{ secrets.BACKEND_APP_NAME }} --environment-name ${{ secrets.BACKEND_ENV_NAME }} --version-label ${{ github.run_id }}
