name: Destroy AWS CDK Infrastructure (& Resources) !!!! DO NOT RUN UNLESS YOU KNOW WHAT YOU ARE DOING !!!! 

on:
  workflow_dispatch:

jobs:
    Destroy:
        runs-on: ubuntu-latest

        steps:
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'

            - name: Install AWS CLI
              run: |
                sudo apt install -y awscli

            - name: Configure AWS Credentials
              run: |
                aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws configure set region 'eu-west-1'

            - name: Install AWS CDK
              run: |
                npm install -g aws-cdk

            - name: Destroy
              working-directory: ./Infrastructure
              run: cdk destroy --require-approval never
